# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "prequery"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = [
	"Clemens Koza <https://github.com/SillyFreak/>"
]
license = "MIT"
description = "library for extracting metadata for preprocessing from a typst document"
# homepage = ""
repository = "https://github.com/SillyFreak/typst-packages/tree/main/prequery"
keywords = ["query", "metadata", "preprocessing"]
categories = ["scripting", "utility"]
disciplines = []
compiler = "0.11.0"
exclude = [
	".github",
	"docs",
	"gallery",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
]

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
